class XPoolEvents {

  static RESOURCE_CREATED = Symbol('XPOOL_EVENT_RESOURCE_CREATED');
  static RESOURCE_CREATION_ERROR = Symbol('XPOOL_EVENT_RESOURCE_CREATION_ERROR');
  static RESOURCE_CREATION_TIMEOUT = Symbol('XPOOL_EVENT_RESOURCE_CREATION_TIMEOUT');
  static RESOURCE_VALIDATED = Symbol('XPOOL_EVENT_RESOURCE_VALIDATED');
  static RESOURCE_VALIDATION_ERROR = Symbol('XPOOL_EVENT_RESOURCE_VALIDATION_ERROR');
  static RESOURCE_VALIDATION_TIMEOUT = Symbol('XPOOL_EVENT_RESOURCE_VALIDATION_TIMEOUT');
  static RESOURCE_ACQUIRED = Symbol('XPOOL_EVENT_RESOURCE_ACQUIRED');
  static RESOURCE_RELEASED = Symbol('XPOOL_EVENT_RESOURCE_RELEASED');
  static RESOURCE_DESTROYED = Symbol('XPOOL_EVENT_RESOURCE_DESTROYED');
  static RESOURCE_DESTRUCTION_ERROR = Symbol('XPOOL_EVENT_RESOURCE_DESTRUCTION_ERROR');
  static RESOURCE_DESTRUCTION_TIMEOUT = Symbol('XPOOL_EVENT_RESOURCE_DESTRUCTION_TIMEOUT');
  static RESOURCE_SEGREGATED = Symbol('XPOOL_EVENT_RESOURCE_SEGREGATED');
}

module.exports = XPoolEvents;
