class XPoolEvents {

  static RESOURCE_CREATED = Symbol('RESOURCE_CREATED');
  static RESOURCE_CREATION_ERROR = Symbol('RESOURCE_CREATION_ERROR');
  static RESOURCE_CREATION_TIMEOUT = Symbol('RESOURCE_CREATION_TIMEOUT');
  static RESOURCE_CREATION_ABANDONED = Symbol('RESOURCE_CREATION_ABANDONED');
  static RESOURCE_VALIDATED = Symbol('RESOURCE_VALIDATED');
  static RESOURCE_VALIDATION_ERROR = Symbol('RESOURCE_VALIDATION_ERROR');
  static RESOURCE_VALIDATION_TIMEOUT = Symbol('RESOURCE_VALIDATION_TIMEOUT');
  static RESOURCE_VALIDATION_ABANDONED = Symbol('RESOURCE_VALIDATION_ABANDONED');
  static RESOURCE_ACQUIRED = Symbol('RESOURCE_ACQUIRED');
  static RESOURCE_ACQUISITION_TIMEOUT = Symbol('RESOURCE_ACQUISITION_TIMEOUT');
  static RESOURCE_RELEASED = Symbol('RESOURCE_RELEASED');
  static RESOURCE_DESTROYED = Symbol('RESOURCE_DESTROYED');
  static RESOURCE_DESTRUCTION_ERROR = Symbol('RESOURCE_DESTRUCTION_ERROR');
  static RESOURCE_DESTRUCTION_TIMEOUT = Symbol('RESOURCE_DESTRUCTION_TIMEOUT');
  static RESOURCE_SEGREGATED = Symbol('RESOURCE_SEGREGATED');
}

module.exports = XPoolEvents;
